### ISSUE TITLE
Unable to override files_path setting

### ISSUE THREAD

**Issue by swichers** [acquia/lightning#278]
**What happens**

When using the `I attach the file "<file>" to "<field>"` step it attempts to upload a file from the lighting profile directory regardless of what is configured in the project's behat.yml.

**behat.yml**

```
default:
  suites:
    default:
      paths:
        - %paths.base%/features
      contexts:
        - Drupal\FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
  extensions:
    Behat\MinkExtension:
      default_session: goutte
      javascript_session: selenium2
      goutte: ~
      files_path: "%paths.base%/media"
```

**What I expect to happen**

I expect the configured path to be used whenever we use the attach file step.

**Cause**

`lightning.behat.inc:setFilePath()` is forcing a Lightning-relative path and by the time we hit the MinkContext implementation of uploading a file we've lost the project setting.
