### ISSUE TITLE
Libraries should be defined relative to lightning

### ISSUE THREAD

**Issue by grasmash** [acquia/lightning#77]
When installing lightning to profiles/contrib/lightning, the media feature is broken.

It seems that the issue stems from Lightning's assumption that it is installed at /profiles/lightning, when in fact it may be installed somewhere else. This assumption is made in the *.libraries.yml files, which specify the required js locations in the following fashion: `/profiles/lightning/libraries/backbone.collectionView/dist/backbone.collectionView.min.js`

Rather that defining these js and css files relative to the docroot, they should be relative to lightning. E.g., `libraries/backbone.collectionView/dist/backbone.collectionView.min.js`. This seems to match the suggested pattern used in examples here: https://www.drupal.org/developing/api/8/assets

**Comment by phenaproxima** [comment]
@grasmash, I have created a new branch with what I hope will fix the problem.

To test it, try to build Lightning from its makefile (build-lightning.make.yml). But first, change it to look like this:

```
api: 2
core: 8.x
includes:
  - drupal-org-core.make.yml
projects:
  lightning:
    type: profile
    download:
      type: git
      branch: libraries_path
      url: https://github.com/acquia/lightning.git
```
